{% set name = "ml-wrappers" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_wrappers-{{ version }}.tar.gz
  sha256: 72e8163b16583bb99398d9d828a24d890a3de51e7da6716cda08ca022013a24c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - python >=3.6
    - scikit-learn
    - scipy

test:
  imports:
    - ml_wrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/ml-wrappers
  summary: Machine Learning Wrappers SDK for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
