{% set name = "ml-wrappers" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_wrappers-{{ version }}.tar.gz
  sha256: 0dd1fd4d57f4c32f83fb939671da2a3499aa52d287b112088a26d15be61970a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas <2
    - python >=3.6
    - scikit-learn
    - scipy

test:
  imports:
    - ml_wrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/ml-wrappers
  summary: Machine Learning Wrappers SDK for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
