{% set name = "ml-wrappers" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_wrappers-{{ version }}.tar.gz
  sha256: 2f5dc4b76bce8f4e2312a9cb519033a936b521f76d0ac8172e8041230e70aa16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas <2
    - python >=3.6
    - scikit-learn
    - scipy

test:
  imports:
    - ml_wrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/ml-wrappers
  summary: Machine Learning Wrappers SDK for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
