{% set name = "ml-wrappers" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ml_wrappers-{{ version }}.tar.gz
  sha256: 004033401c6563ed281b57f150f7ea6be9dfab556a309913cc0c1189d1a3c40e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pandas <2
    - python >={{ python_min }}
    - scikit-learn
    - scipy

test:
  imports:
    - ml_wrappers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/ml-wrappers
  summary: Machine Learning Wrappers SDK for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
