schema_version: 1

context:
  name: ml-wrappers
  version: 0.5.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ml_wrappers-${{ version }}.tar.gz
  sha256: c5013a576fe065a2f91e33f38de25f59f227f3fba6d55cc2d34d1ac7e404a1d2

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - numpy
    - pandas <2
    - python >=${{ python_min }}
    - scikit-learn
    - scipy

tests:
  - python:
      imports:
        - ml_wrappers
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Machine Learning Wrappers SDK for Python
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/microsoft/ml-wrappers

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
