schema_version: 1

context:
  name: ml-wrappers
  version: 0.6.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ml_wrappers-${{ version }}.tar.gz
  sha256: 7b2b1faf66d77448a6924ac9bddb87e371cef045b4f6d58f353da4bb78c3e693

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - numpy
    - pandas
    - python >=${{ python_min }}
    - scikit-learn
    - scipy
    - packaging
tests:
  - python:
      imports:
        - ml_wrappers
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Machine Learning Wrappers SDK for Python
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/microsoft/ml-wrappers

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
